
// This file is auto-generated by set-env.js
export const environment = {
  production: true,
  firebase: {
    apiKey: 'AIzaSyBkYAMWRe6ueXQ8H3QSaw9afRHRi7LVZow',
    authDomain: 'bookcompany-43145.firebaseapp.com',
    projectId: 'bookcompany-43145',
    storageBucket: 'bookcompany-43145.firebasestorage.app',
    messagingSenderId: '227622370451',
    appId: '1:227622370451:web:a0f78d2b3486f0e1f22166',
    measurementId: 'G-N893829LKH',
    databaseURL: 'https://bookcompany-43145-default-rtdb.firebaseio.com/'
  },
  googleMapsApiKey: 'YOUR_GOOGLE_MAPS_API_KEY_HERE'
};
