name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - solo-main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install exact dependencies and run your full build process
      - run: npm ci --legacy-peer-deps && npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKCOMPANY_43145 }}
          channelId: live
          projectId: bookcompany-43145
